In [30]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key
from config import weather_api_key

In [ ]:
# Starting URL for Google map API call.
url = "" + weather_api_key
print(url)

In [31]:
# Import the WeatherPy_vacation.csv file from Part 1 as a new DataFrame
city_data_df = pd.read_csv("WeatherPy_vacation.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches (last 3 hrs),Snow inches (last 3 hrs)
0,0,Punta Arenas,CL,2019-11-13 18:05:32,-53.16,-70.91,59.00,76,75,14.99,light rain,0.0,0.0
1,1,Spokane,US,2019-11-13 18:02:05,47.66,-117.42,39.99,100,90,11.41,mist,0.0,0.0
2,2,Yanliang,CN,2019-11-13 18:05:33,34.66,109.22,45.00,92,0,2.24,clear sky,0.0,0.0
3,3,Ahuimanu,US,2019-11-13 18:05:33,21.44,-157.84,77.00,88,20,2.77,few clouds,0.0,0.0
4,4,Albany,US,2019-11-13 18:05:33,42.65,-73.75,27.00,45,20,9.17,few clouds,0.0,0.0

In [32]:
# Filter the DataFrame
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 45
What is the maximum temperature you would like for your trip? 70

In [33]:
raining = str(input("Do you want it to be raining? (yes/no) "))

snowing = str(input("Do you want it to be snowing? (yes/no) "))

Do you want it to be raining? (yes/no) no
Do you want it to be snowing? (yes/no) no

In [34]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches (last 3 hrs),Snow inches (last 3 hrs)
0,0,Punta Arenas,CL,2019-11-13 18:05:32,-53.16,-70.91,59.00,76,75,14.99,light rain,0.0,0.0
2,2,Yanliang,CN,2019-11-13 18:05:33,34.66,109.22,45.00,92,0,2.24,clear sky,0.0,0.0
5,5,Cheyenne,US,2019-11-13 18:07:58,41.14,-104.82,59.00,29,1,17.22,clear sky,0.0,0.0
10,10,Ushuaia,AR,2019-11-13 18:05:34,-54.81,-68.31,60.80,54,20,14.99,few clouds,0.0,0.0
13,13,Tiznit,MA,2019-11-13 18:08:01,29.70,-9.73,65.21,44,100,3.29,overcast clouds,0.0,0.0

In [35]:
if raining == "yes":
    preferred_cities_df.amend = city_data_df.loc[(city_data_df["Rain inches (last 3 hrs)"] >0.00)]
else:
    preferred_cities_df.amend = city_data_df.loc[(city_data_df["Rain inches (last 3 hrs)"] ==0.00)]
if snowing == "yes":
    preferred_cities_df.amend = city_data_df.loc[(city_data_df["Snow inches (last 3 hrs)"] >0.00)]
else:
    preferred_cities_df.amend = city_data_df.loc[(city_data_df["Snow inches (last 3 hrs)"] ==0.00)]    
preferred_cities_df.head()

/Users/Hunterwelsch/anaconda2/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:4: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  after removing the cwd from sys.path.

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches (last 3 hrs),Snow inches (last 3 hrs)
0,0,Punta Arenas,CL,2019-11-13 18:05:32,-53.16,-70.91,59.00,76,75,14.99,light rain,0.0,0.0
2,2,Yanliang,CN,2019-11-13 18:05:33,34.66,109.22,45.00,92,0,2.24,clear sky,0.0,0.0
5,5,Cheyenne,US,2019-11-13 18:07:58,41.14,-104.82,59.00,29,1,17.22,clear sky,0.0,0.0
10,10,Ushuaia,AR,2019-11-13 18:05:34,-54.81,-68.31,60.80,54,20,14.99,few clouds,0.0,0.0
13,13,Tiznit,MA,2019-11-13 18:08:01,29.70,-9.73,65.21,44,100,3.29,overcast clouds,0.0,0.0

In [42]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head()

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Punta Arenas,CL,59.00,light rain,-53.16,-70.91,
2,Yanliang,CN,45.00,clear sky,34.66,109.22,
5,Cheyenne,US,59.00,clear sky,41.14,-104.82,
10,Ushuaia,AR,60.80,few clouds,-54.81,-68.31,
13,Tiznit,MA,65.21,overcast clouds,29.70,-9.73,

In [43]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to the params dictionary as values to the location key.
    params["location"] = f"{lat},{lng}"
    
    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    
   # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")
        
hotel_df.head(10)

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Punta Arenas,CL,59.00,light rain,-53.16,-70.91,Hotel Dreams Del Estrecho
2,Yanliang,CN,45.00,clear sky,34.66,109.22,Pod Inn Xi'an Yanliang Renmin Road
5,Cheyenne,US,59.00,clear sky,41.14,-104.82,The Historic Plains Hotel
10,Ushuaia,AR,60.80,few clouds,-54.81,-68.31,Albatros Hotel
13,Tiznit,MA,65.21,overcast clouds,29.70,-9.73,Hotel Café Restaurant Assaka
18,Hobart,AU,52.00,overcast clouds,-42.88,147.33,St Ives Apartments
19,Castro,CL,64.40,broken clouds,-42.48,-73.76,Hotel Esmeralda
21,Busselton,AU,66.99,clear sky,-33.64,115.35,Observatory Guest House
22,Wanxian,CN,52.93,broken clouds,30.80,108.39,7Days Inn Chongqing Shiqiaopu
24,Jalu,LY,63.97,clear sky,29.03,21.55,Jalu Hotel

In [44]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [46]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
<dt>Current Description/dt><dd>{Current Description}</dd>
</dl>
"""

# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

# Add a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=2)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [47]:
# Create the output file (CSV).
output_data_file = "WeatherPy_vacation.csv"
# Export the City_Data into a CSV.
hotel_df.to_csv(output_data_file, index_label="City_ID")

In [ ]:
WeatherPy_vacation_map.png